### PR TITLE
Add failing excerpt tests

### PR DESCRIPTION
**Pull request by benbalter**
@parkr a failing test to check https://github.com/jekyll/jekyll-feed/pull/57, feel free to hijack this branch/pr if you'd like. Not sure what's going on.

### CODE REVIEW

**Comment by parkr** [comment]
@benbalter For the "author detail" post, the excerpt is created automatically. That tells me why `:111` is failing. If you set it to `""`, then I had to make a modification to the `feed.xml`. As for the first one, it's because you need to call `#content`. 

Sorry for not writing a test for that one. Total noob move. :/

**Comment by benbalter** [comment]
Nice. Thanks. Will get this (selfishly) deployed.

**Comment by parkr** [comment]
Side effect of dogfooding: selfish is good for all.

**Comment by benbalter** [comment]
Good news: This feature now has tests.

Bad news: I'm an idiot. `/feed` on my site wasn't generated by this plugin, but a stray XML file. :hurtrealbad:

**Comment by parkr** [comment]
> Bad news: I'm an idiot. /feed on my site wasn't generated by this plugin, but a stray XML file.

Oh no! I didn't even think to check. Well, now are you using jekyll-feed?!?!

**Pull request merged**
