### PR TITLE
chore: use Dir to list source files

### PR DESCRIPTION
**Pull request by DirtyF**
https://piotrmurach.com/articles/writing-a-ruby-gem-specification/

### CODE REVIEW

**Comment by ashmaroli** [comment]
Is your motivation behind this to follow a convention or to just bundle the necessary files in the gem?
If it is the latter case, then IMHO the gem contents ought to roughly be:
```diff
  lib/**/*
- script/**/*
- spec/**/*
- .gitignore
- .rspec
- .rubocop.yml
- .travis.yml
- appveyor.yml
- Gemfile
  History.markdown
- Rakefile
  README.md
```

**Comment by DirtyF** [comment]
@ashmaroli looks like it would be easier to only add lib and Markdown files :)

**Comment by ashmaroli** [comment]
Yep. `:select` instead of `:reject`.. :wink:

**Comment by DirtyF** [comment]
@ashmaroli found an even simpler way to list files with `Dir` thanks to @piotrmurach

**Comment by ashmaroli** [comment]
@jekyllbot: merge +dev

**Pull request merged**
