### PR TITLE
Consolidate regexs

### PR DESCRIPTION
**Pull request by pathawks**
Inspired by @benbalter, I have consolidated three regular expressions into one.

### CODE REVIEW

**Comment by parkr** [comment]
Are each of these tested?

**Comment by pathawks** [comment]
The whole point of all of these was to strip unnecessary whitespace, which [there is a test for](https://github.com/jekyll/jekyll-feed/blob/master/spec/jekyll-feed_spec.rb#L35-L38).

**Comment by parkr** [comment]
Excellent.

**Comment by parkr** [comment]
Thanks! :tada:

**Pull request merged**
