### PR TITLE
feed.xml: check to ensure the post excerpt isn't blank before outputting

### LINKED ISSUE #52: `<summary>` is always blank on jekyllrb.com
My hunch is that `if page.excerpt` when `page.excerpt` is `""` is still truthy. We should make sure it's also not empty.

screen shot 2015-05-28 at 10 39 09 am

### PR DESCRIPTION
**Pull request by parkr**
Fixes #52

### CODE REVIEW

**Comment by benbalter** [comment]
> `and post.excerpt != blank`

That works? Huh. Nice.

**Comment by parkr** [comment]
Thanks, Ben!

**Comment by benbalter** [comment]
@parkr is this tested anywhere? Looking at [my own feed](http://ben.balter.com/feed/), it looks like this may have nuked excerpts entirely.

**Comment by parkr** [comment]
> Looking at my own feed, it looks like this may have nuked excerpts entirely.

Hmmmmmm. Will look at your PR and see what's up.

**Pull request merged**
