### PR TITLE
Update feed.xml

### LINKED ISSUE #161: 0.9.0: invalid xml
```
This feed does not validate.

    line 1, column 79: XML parsing error: <unknown>:1:79: not well-formed (invalid token)
```

The problem is a missing space.

```xml
<?xml version="1.0" encoding="utf-8"?><feed xmlns="http://www.w3.org/2005/Atom"xml:lang="en">
                                                                               ^
```

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #161

### CODE REVIEW

**Comment by benbalter** [comment]
@jekyllbot: merge +minor.

**Comment by benbalter** [comment]
THanks @XhmikosR!

**Comment by pathawks** [comment]
I wonder if we would be better off relaxing our [`MINIFY_REGEX`](https://github.com/jekyll/jekyll-feed/blob/v0.9.0/lib/jekyll-feed/generator.rb#L19)?

**Comment by XhmikosR** [comment]
That seems the proper solution. I just wanted a quick fix since the current
release was broken for me on Firefox.

**Pull request merged**
