### PR TITLE
Remove trailing slash from feed ID

### PR DESCRIPTION
**Pull request by pathawks**
See #158

### CODE REVIEW

**Comment by pathawks** [comment]
Rubocop error is unrelated

**Comment by benbalter** [comment]
@jekyllbot: merge +minor.

**Comment by benbalter** [comment]
Nice catch @pathawks! 🌷 🐢 🌮

**Comment by benbalter** [comment]
Think it's worth releasing a 0.9.0? ~35 commits on master.

**Comment by pathawks** [comment]
I think @ashmaroli and I noticed it at the exact same moment.

I think it would be fine to release a 0.9.0

We should mention somewhere that _all_ feed IDs will change now. That may result in previously read items appearing as unread in feed readers. Nothing that can be done to prevent that, however.

**Comment by ashmaroli** [comment]
or how about a `v1.0`? esp. with the namespace change n all.. `Jekyll::JekyllFeed` is `JekyllFeed::Generator` now.. Doesn't that qualify as a major change in API?
Please enlighten me.

Moreover, I thought removing `/` was just a bug-fix, but apparently its a `Minor Enhancement`. This became clear by reading Pat's comment above though..

**Comment by pathawks** [comment]
Public API is not considered stable until `1.0.0`. According to [semver.org](http://semver.org/#spec-item-4):

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

We are still in the initial development stage. We will ship `1.0.0` when things are stable. We are close.

**Comment by ashmaroli** [comment]
Okay. Thanks :smiley:

**Pull request merged**
