### PR TITLE
Add support for page.description in front matter to become entry `<summary>`

### LINKED ISSUE #216: Use page.description for summary element, falling back to page.excerpt
[Jekyll SEO Tag](https://github.com/jekyll/jekyll-seo-tag) prioritises the `page.description` front matter value over `page.excerpt` ([see PR](https://github.com/jekyll/jekyll-seo-tag/commit/6dab82639ea393f93033efc5e3f5005e864de2b4)). It would be great to also have this for the feed item's `summary` element.

While `excerpt` typically contains a truncated snippet from the beginning of the post, `description` provides a place for the author to better summarise the content.

### PR DESCRIPTION
**Pull request by mohd-akram**
Closes #216.

### CODE REVIEW

**Comment by parkr** [comment]
I’m not sure I understand why you would use a different field here, namely why you would use `description` instead of `excerpt`. Jekyll allows you to overwrite `excerpt` in front matter, so why not just overwrite the excerpt for the post or page in question?

**Comment by mohd-akram** [comment]
I use `description` because it's supported by `jekyll-seo-tag` (see the issue above) and because overriding `excerpt` feels weird. `title` and `description` together are also analogous to their HTML counterparts.

**Comment by benbalter** [comment]
👋😄 I came here to request the same feature. 

Since Jekyll SEO Tag supports `title` + `description`, I add short 1-2 sentence descriptions to each post which serve as a concise summary of the post's content. By using `excerpt` and only `excerpt`, Jekyll Feed either only outputs the post body up to the first line break or requires site maintainers to duplicate summaries across both the `excerpt` and `description` fields for all posts. 

:+1: to preferring `description` if it's present to bring things a bit closer in line with the way Jekyll SEO Tag treats front matter.

**Comment by parkr** [comment]
jekyll-seo-tag has a field called "description" which uses `page.description` then `page.excerpt` and finally falls back  to the site description:

https://github.com/jekyll/jekyll-seo-tag/blob/c658a8dd9d94520c090547b164e643441df8e62f/lib/jekyll-seo-tag/drop.rb#L90-L94

**Review by parkr — APPROVED** [review]

**Comment by parkr** [comment]
@jekyllbot: merge +minor

**Pull request merged**
