### PR TITLE
Allow disabling of jekyll-feed while in development

### PR DESCRIPTION
**Pull request by sylhare**
SInce https://github.com/jekyll/jekyll-feed/pull/346 was not getting any traction, I addressed the code review comments and created this PR.

### CODE REVIEW

**Comment by sylhare** [comment]
Oh it seems I need approval to run the workflow, @parkr would you be able to take a look. Thanks!

**Comment by sylhare** [comment]
Ah it gets:

```

lib/jekyll-feed/generator.rb:9:5: C: Metrics/AbcSize: Assignment Branch Condition size for generate is too high. [<5, 23, 9> 25.2/21]
    def generate(site) ...
    ^^^^^^^^^^^^^^^^^^
lib/jekyll-feed/generator.rb:9:5: C: Metrics/CyclomaticComplexity: Cyclomatic complexity for generate is too high. [8/7]
    def generate(site) ...
    ^^^^^^^^^^^^^^^^^^
```

**Comment by parkr** [comment]
@jekyllbot: merge +minor

**Comment by tadamcz** [comment]
This change appears in the README on the `master` branch, but has not been released, which can be confusing. Especially since earlier versions fail silently.

I had to use:

```Gemfile
gem 'jekyll-feed', git: "git@github.com:jekyll/jekyll-feed.git"
```

**Comment by parkr** [comment]
0.17.0 is out now.

**Pull request merged**
