### PR TITLE
Replace newlines with space

### PR DESCRIPTION
**Pull request by pathawks**
Currently failing tests because this method does not remove trailing space from the end of the title if the title ends with a newline.

Not sure what to do about that without chasing our own tail. Maybe we just don't strip newlines at all?

#66

### CODE REVIEW

**Comment by parkr** [comment]
Is there a "strip" filter we could use?

**Comment by pathawks** [comment]
Shopify has one, but Jekyll does not.

**Comment by parkr** [comment]
> Shopify has one, but Jekyll does not.

¡ABSURD! Is it in Liquid 3 only, maybe?

**Comment by pathawks** [comment]
[Looks that way](https://github.com/Shopify/liquid/commit/d2827bfa76801d0e8b104ab28703ce86164d5253)

**Comment by mattr-** [comment]
welp. time to upgrade :troll:

**Comment by parkr** [comment]
Will release a new beta. Maybe I can get some time this week...

**Comment by pathawks** [comment]
Using the `strip` works for Jekyll 3.

Jekyll 2 will not have trailing whitespace removed, but calling a filter that doesn't exist doesn't break anything either with the relaxed Liquid parsing.

**Comment by pathawks** [comment]
The other option would be to just add our own Liquid filter to collapse whitespace

```ruby
  def collapse_whitespace(input)
    input.to_s.gsub(/\s+/, ' ').strip
  end
```

:question:

**Comment by parkr** [comment]
Any liquid filters we make here will be globally available, just a head's up.

**Comment by pathawks** [comment]
> Any liquid filters we make here will be globally available, just a head's up.

Is that to be avoided?

**Comment by parkr** [comment]
@pathawks Would you please add a test for this?

**Comment by pathawks** [comment]
Test added :+1:

**Pull request merged**
