### PR TITLE
Add a `feedsafe` filter

### PR DESCRIPTION
**Pull request by pathawks**
This is a first step toward addressing #22

### CODE REVIEW

**Comment by benbalter** [comment]
What's the downside of having classes in an Atom feed? Same with protocol-relative URLs?

**Comment by pathawks** [comment]
I'm not sure classes would have much meaning without whatever stylesheet goes with the site, but I suppose they're probably not hurting much either.

I don't know how offline feed readers deal with protocol-relative URLs; perhaps filtering them is unnecessary? I guess we could ignore them until it causes a real world problem.

**Comment by pathawks** [comment]
Also of note, WordPress - in addition to filtering content of the feed - [includes `xml:base`](https://github.com/WordPress/WordPress/blob/master/wp-includes/feed-atom.php#L72) so that relative permalinks can still be relative to something.

**Comment by pathawks** [comment]
Closing this, as #43 seems to be good enough.

**Pull request closed without merging**
